### ISSUE TITLE
SDLongClipModel.__init__() got an unexpected keyword argument 'model_options'

### ISSUE THREAD

**Issue by yhys999** [SeaArtLab/ComfyUI-Long-CLIP#15]
![image](https://github.com/user-attachments/assets/519d1a16-a5ac-4902-9e14-f860daaf51e1)
SD1.5 workflow bug

**Comment by zer0int** [comment]
I could not reproduce the issue. In theory, this should be fixed due to handling `**kwargs`. 

Please make sure you have the latest version: [https://github.com/zer0int/ComfyUI-Long-CLIP](https://github.com/zer0int/ComfyUI-Long-CLIP)

**Comment by Kasr40k** [comment]
I have the same issue with my SD1.5 Workflow. Here's the error in the log: 

**2024-09-03 19:38:31,623 - root - ERROR - !!! Exception during processing !!! SDLongClipModel.__init__() got an unexpected keyword argument 'model_options'
2024-09-03 19:38:31,626 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip.py", line 406, in do
    clip = CLIP(clip_target, embedding_directory=embedding_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 83, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
TypeError: SDLongClipModel.__init__() got an unexpected keyword argument 'model_options'**

**Comment by zer0int** [comment]
Just a heads up: ComfyUI now natively supports Long-CLIP. You can just use it from the normal loader node. Kind regards!
