### ISSUE TITLE
"Import Failed" via ComfyUI Manager - ModuleNotFoundError: No module named 'ftfy'

### ISSUE THREAD

**Issue by darthbodacious** [SeaArtLab/ComfyUI-Long-CLIP#18]
Hello! I'm unable to install this via the ComfyUI Manager.

When I attempt to do so, I get this error when ComfyUI is restarted:
`ModuleNotFoundError: No module named 'ftfy'`

I tried:
- uninstalling and reinstalling ComyUI-Long-CLIP
- adding a `requirements.txt` to the ComfyUI-Long-CLIP folder with `ftfy` in it
- trying to install `ftfy` myself in the embedded python folder (it was already installed)

I'm somewhat new to the whole ComfyUI system, but googling around didn't seem to indicate this was common. It could definitely be something odd on my end, but this is the first node that didn't work "out of the box" for me, so I'm making this report!

I'm using a Windows 11 machine and the portable version of ComfyUI for what it's worth!

Here's the full traceback:

```
Traceback (most recent call last):
  File "C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\__init__.py", line 1, in <module>
    from . import long_clip as long_clip
  File "C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip.py", line 1, in <module>
    from .long_clip_model import longclip
  File "C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip_model\longclip.py", line 14, in <module>
    from .simple_tokenizer import SimpleTokenizer as _Tokenizer
  File "C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip_model\simple_tokenizer.py", line 6, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

Cannot import C:\Users\name\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Long-CLIP module for custom nodes: No module named 'ftfy'
```

**Comment by zer0int** [comment]
Ah, the Desktop folder. There is something dodgy in Windows when trying to run stuff in the Desktop folder, actually...
Can you try moving the entire ComfyUI e.g. to "C:\ComfyUI_windows_portable", for example?

Then find the `python.exe` and `cd` to that folder and do `python.exe -m pip install ftfy` - hopefully that will work!

**Comment by darthbodacious** [comment]
Still no dice, I'm afraid! I tried force reinstalling `ftfy` since it was already found in that location.

Also tried simple stuff like a reset of the computer and whatnot. Don't wanna waste folks time on it if it's just my machine, though, so I'll see if I can install elsewhere and if I have the same issue.

**Comment by okolenmi** [comment]
I have the same issue on Linux. I fixed it, but it's not something easy to do as you need to activate ComfyUI virtual environment first (usually it's folder named "venv" that contains all dependencies: 
`source ComfyUI/venv/bin/activate`
and then this line: 
`python3 -m pip install ftfy`

**Comment by zer0int** [comment]
Hey everyone,
LongCLIP is now (since 2 months or so?) natively supported in ComfyUI - you can just load it in the normal / native / included CLIP loader node, e.g. where you load T5 + CLIP-L, or CLIP-G and CLIP-L.

You can just select a LongCLIP instead of a CLIP-L and you're all set! :-)

King regards!

**Comment by miasik** [comment]
> Hey everyone, LongCLIP is now (since 2 months or so?) natively supported in ComfyUI - you can just load it in the normal / native / included CLIP loader node, e.g. where you load T5 + CLIP-L, or CLIP-G and CLIP-L.
> You can just select a LongCLIP instead of a CLIP-L and you're all set! :-)

Don't we need to use a special node now?
