### ISSUE TITLE
Error occurred when executing SeaArtLongClip:  invalid load key, '\xe0'.

### ISSUE THREAD

**Issue by magicwang1111** [SeaArtLab/ComfyUI-Long-CLIP#8]
![image](https://github.com/SeaArtLab/ComfyUI-Long-CLIP/assets/131337141/7b890b5a-5c5b-4c2c-a46d-b044265ffd69)
cant use

**Comment by pcrii** [comment]
same

!!! Exception during processing!!! invalid load key, '\xe0'.
Traceback (most recent call last):
  File "/home/phaulty/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/phaulty/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/phaulty/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/phaulty/ComfyUI/custom_nodes/ComfyUI-Long-CLIP/long_clip.py", line 406, in do
    clip = CLIP(clip_target, embedding_directory=embedding_directory)
  File "/home/phaulty/ComfyUI/comfy/sd.py", line 105, in __init__
    self.cond_stage_model = clip(**(params))
  File "/home/phaulty/ComfyUI/custom_nodes/ComfyUI-Long-CLIP/long_clip.py", line 24, in __init__
    self.transformer, _ = longclip.load(version, device=device)
  File "/home/phaulty/ComfyUI/custom_nodes/ComfyUI-Long-CLIP/long_clip_model/longclip.py", line 68, in load
    state_dict = torch.load(model_path, map_location="cpu")
  File "/home/phaulty/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/phaulty/ComfyUI/venv/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xe0'.

**Comment by pcrii** [comment]
i realized i wasnt using the long clip model that is linked in the repo so i fetched it and now i get a different error

`!!! Exception during processing!!! 'SDLongClipModel' object has no attribute 'dtypes'
Traceback (most recent call last):
  File "/home/phaulty/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/phaulty/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/phaulty/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/phaulty/ComfyUI/custom_nodes/ComfyUI-Long-CLIP/long_clip.py", line 406, in do
    clip = CLIP(clip_target, embedding_directory=embedding_directory)
  File "/home/phaulty/ComfyUI/comfy/sd.py", line 107, in __init__
    for dt in self.cond_stage_model.dtypes:
  File "/home/phaulty/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SDLongClipModel' object has no attribute 'dtypes'
`

**Comment by toyxyz** [comment]
Same here!

AttributeError: 'SDLongClipModel' object has no attribute 'dtypes'

**Comment by mityarko** [comment]
also(((
```
'SDLongClipModel' object has no attribute 'dtypes'
```

**Comment by Pazerniusz** [comment]
add this
self.dtypes = [param.dtype for param in self.transformer.parameters()]
in section def __init__ just above 
def freeze(self):
![image](https://github.com/user-attachments/assets/bb1dcaeb-c82a-4b1e-91f1-4e742519eaa7)
