### ISSUE TITLE
Not Loading in the current ComfyUI

### ISSUE THREAD

**Issue by Piscabo** [SeaArtLab/ComfyUI-Long-CLIP#9]
I currently have this issue, don't know what is causing it?
ComfyUI: 2324[537f35](2024-07-02)
Manager: V2.44.1

Traceback (most recent call last):
  File "H:\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\__init__.py", line 1, in <module>
    from . import long_clip as long_clip
  File "H:\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip.py", line 1, in <module>
    from .long_clip_model import longclip
  File "H:\ComfyUI\custom_nodes\ComfyUI-Long-CLIP\long_clip_model\longclip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\comfyVENV\Lib\site-packages\pkg_resources\__init__.py)

![image](https://github.com/SeaArtLab/ComfyUI-Long-CLIP/assets/123719842/cba5e69e-f86c-41ba-b5b8-a2825431bde1)

**Comment by KewkLW** [comment]
Change from "pkg_resources import packaging" to "import packaging" in longclip.py

**Comment by Piscabo** [comment]
> Change from "pkg_resources import packaging" to "import packaging" in longclip.py

Can someone just commit this change, every time I update I have to do this manually. Or is this repo no longer maintained?
